name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'  # Sunday at 06:15 UTC
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show event that triggered the workflow
        run: echo "Event: ${{ github.event_name }}"

      - name: Show current branch
        run: echo "Branch: ${{ github.ref }}"

      - name: List all files in the repository
        run: ls -R
